/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ChangeMenuButton: typeof import('./src/components/TopBar/ChangeMenuButton.vue')['default']
    ClientMessageBox: typeof import('./src/components/ChatContainer/ClientMessageBox.vue')['default']
    CollapseSider: typeof import('./src/components/Sider/CollapseSider.vue')['default']
    FavoriteFolder: typeof import('./src/components/Sider/FavoriteFolder.vue')['default']
    FormLogin: typeof import('./src/components/FormLogin.vue')['default']
    FormRegister: typeof import('./src/components/FormRegister.vue')['default']
    NButton: typeof import('naive-ui')['NButton']
    NCard: typeof import('naive-ui')['NCard']
    NCollapse: typeof import('naive-ui')['NCollapse']
    NCollapseItem: typeof import('naive-ui')['NCollapseItem']
    NDropdown: typeof import('naive-ui')['NDropdown']
    NFlex: typeof import('naive-ui')['NFlex']
    NFloatButton: typeof import('naive-ui')['NFloatButton']
    NForm: typeof import('naive-ui')['NForm']
    NFormItem: typeof import('naive-ui')['NFormItem']
    NIcon: typeof import('naive-ui')['NIcon']
    NInput: typeof import('naive-ui')['NInput']
    NInputGroup: typeof import('naive-ui')['NInputGroup']
    NMessageProvider: typeof import('naive-ui')['NMessageProvider']
    NResult: typeof import('naive-ui')['NResult']
    NSelect: typeof import('naive-ui')['NSelect']
    NSkeleton: typeof import('naive-ui')['NSkeleton']
    NSpace: typeof import('naive-ui')['NSpace']
    NTooltip: typeof import('naive-ui')['NTooltip']
    ReasonContainer: typeof import('./src/components/ChatContainer/ReasonContainer.vue')['default']
    RecentFolder: typeof import('./src/components/Sider/RecentFolder.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ServeMessageBox: typeof import('./src/components/ChatContainer/ServeMessageBox.vue')['default']
    SSTbtn: typeof import('./src/components/STT/SSTbtn.vue')['default']
    TalkInputBox: typeof import('./src/components/ChatContainer/TalkInputBox.vue')['default']
    TopBar: typeof import('./src/components/TopBar/TopBar.vue')['default']
  }
}
